# Generated by Django 4.0.5 on 2022-06-07 15:42

from django.db import migrations

from tools.core import Sky

import requests


def insert_data(apps, schema_editor):
    Planet = apps.get_model("sky", "Planet")
    Moon = apps.get_model("sky", "Moon")
    Asteroid = apps.get_model("sky", "Asteroid")

    Moon.objects.all().delete()
    Planet.objects.all().delete()
    Asteroid.objects.all().delete()

    data = requests.get("https://api.le-systeme-solaire.net/rest/bodies").json()
    sky = Sky.from_raw(data)

    for raw_planet in sky.get_planets():
        orm_planet = Planet.objects.create(name=raw_planet.name, polar_radius=raw_planet.polar_radius)
        Moon.objects.bulk_create([Moon(mass=raw_moon.mass, planet=orm_planet) for raw_moon in raw_planet.moons])


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_alter_moon_mass'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
