# Generated by Django 4.0.5 on 2022-06-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0002_alter_moon_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moons', to='sky.planet'),
        ),
    ]
